server:
  port: ${PORT:8080}

spring:
  application:
    name: todo-service
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.todo: DEBUG
    org.springframework.web: DEBUG
