# Production Profile Configuration
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tododb}?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.todo: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
