spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: agbamoh@gmail.com
    password: yqorlytumeirkehi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

app:
  email:
    from: agbamoh@gmail.com
    verification:
      code-expiry-minutes: 15
    reminder:
      hours-before: 24