# Production Profile Configuration
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://db.audjuuqtyfwharjbazmx.supabase.co:5432/postgres?sslmode=require&sslcert=&sslkey=&sslrootcert=}
    username: postgres
    password: mohamad123
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: HikariCP
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

logging:
  level:
    com.todo: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
