spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: agbamoh@gmail.com
    password: yqorlytumeirkehi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

app:
  email:
    from: agbamoh@gmail.com
    verification:
      code-expiry-minutes: 15
    reminder:
      hours-before: 24