# Production Profile Configuration
spring:
  datasource:
    url: jdbc:postgresql://db.audjuuqtyfwharjbazmx.supabase.co:5432/postgres
    username: postgres
    password: mohamad123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

logging:
  level:
    com.todo: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
