server:
  port: ${PORT:8081}

spring:
  application:
    name: todo-service
  profiles:
    active: prod
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.todo: DEBUG
    org.springframework.web: DEBUG

# JWT settings
jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong}
  expiration: ${JWT_EXPIRATION:86400000}

# Email settings
app:
  email:
    from: ${EMAIL_FROM:your-app@example.com}
    verification:
      code-expiry-minutes: 15
    reminder:
      hours-before: 24