spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tododb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  mail:
    # Resend configuration (easier setup, better free tier)
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_API_KEY:your-resend-api-key}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 10000
          connectiontimeout: 10000
          ssl:
            trust: smtp.resend.com
          # Additional Resend-specific settings
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory

# JWT settings
jwt:
  secret: ${JWT_SECRET:myVeryLongSecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLong}
  expiration: ${JWT_EXPIRATION:86400000}

# Resend API configuration
resend:
  api:
    key: ${RESEND_API_KEY:your-resend-api-key}

app:
  email:
    from: ${RESEND_FROM_EMAIL:your-email@gmail.com}
    verification:
      code-expiry-minutes: 15
    reminder:
      hours-before: 24