spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/todo_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: agbamoh@gmail.com
    password: yqorlytumeirkehi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

app:
  email:
    from: agbamoh@gmail.com
    verification:
      code-expiry-minutes: 15
    reminder:
      hours-before: 24